### ISSUE TITLE
Password cannot be shown in KeePass application after Export

### ISSUE THREAD

**Issue by ofersuli** [kindahl/libkeepass#2]
keepass::Key key("password");
keepass::KdbxFile file;
std::unique_ptr<keepass::Database> db = file.Import("in.kdbx", key);
file.Export("out.kdbx", *db.get(), key);

Creating the file "in.kdbx" with the KeePass 2 application.
Then running the code above (from the Using paragraph in the Readme file) outputs the file "out.kdbx" that when is opened with KeePass 2 application, the password of any entry is shown in Base64 instead of the explicit password.

**Comment by ofersuli** [comment]
I've fixed this issue and created a pull request. please approve.
The problem was that password value's Protected attribute was set with the boolean true value, which is written to the xml as "true", when it should be "True".

**Comment by kindahl** [comment]
I can confirm the issue. Would you please also address the other booleans written to the XML? From what I can tell there are two more places that needs to be fixed.

**Comment by kindahl** [comment]
Thanks for fixing, I've now merged your fixes!
