### ISSUE TITLE
Dont compiling

### ISSUE THREAD

**Issue by PR070CRYP70N1C** [kindahl/libkeepass#5]
make -j8
mkdir -p build/debug/obj
g++ -MMD -g -DDEBUG -std=c++11 -Wall -Wextra -Werror -c -o build/debug/obj/kdb.o src/kdb.cc
mkdir -p build/debug/obj/test
mkdir -p build/debug/obj/test
mkdir -p build/debug/obj/test
g++ -MMD -g -DDEBUG -Isrc/ -std=c++11 -Wall -Wextra -Werror -c -o build/debug/obj/test/cipher.o test/cipher.cc
g++ -MMD -g -DDEBUG -Isrc/ -std=c++11 -Wall -Wextra -Werror -c -o build/debug/obj/test/iterator.o test/iterator.cc
g++ -MMD -g -DDEBUG -Isrc/ -std=c++11 -Wall -Wextra -Werror -c -o build/debug/obj/test/kdb.o test/kdb.cc
mkdir -p build/debug/obj/test
mkdir -p build/debug/obj/test
mkdir -p build/debug/obj/test
g++ -MMD -g -DDEBUG -Isrc/ -std=c++11 -Wall -Wextra -Werror -c -o build/debug/obj/test/kdbx.o test/kdbx.cc
g++ -MMD -g -DDEBUG -Isrc/ -std=c++11 -Wall -Wextra -Werror -c -o build/debug/obj/test/stream.o test/stream.cc
g++ -MMD -g -DDEBUG -Isrc/ -std=c++11 -Wall -Wextra -Werror -c -o build/debug/obj/test/util.o test/util.cc
src/kdb.cc: В lambda функции:
src/kdb.cc:688:22: ошибка: «numeric_limits» не является элементом «std»
  688 |     if (level > std::numeric_limits<uint16_t>::max()) {
      |                      ^~~~~~~~~~~~~~
src/kdb.cc:688:45: ошибка: expected primary-expression before «>» token
  688 |     if (level > std::numeric_limits<uint16_t>::max()) {
      |                                             ^
src/kdb.cc:688:48: ошибка: «::max» has not been declared; did you mean «std::max»?
  688 |     if (level > std::numeric_limits<uint16_t>::max()) {
      |                                                ^~~
      |                                                std::max
In file included from /usr/include/c++/11.1.0/algorithm:62,
                 from src/util.hh:20,
                 from src/entry.hh:27,
                 from src/group.hh:24,
                 from src/database.hh:24,
                 from src/kdb.hh:24,
                 from src/kdb.cc:19:
/usr/include/c++/11.1.0/bits/stl_algo.h:3467:5: замечание: «std::max» declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
src/kdb.cc:695:28: ошибка: «numeric_limits» не является элементом «std»
  695 |     if (num_groups == std::numeric_limits<decltype(num_groups)>::max()) {
      |                            ^~~~~~~~~~~~~~
src/kdb.cc:695:43: ошибка: expected primary-expression before «decltype»
  695 |     if (num_groups == std::numeric_limits<decltype(num_groups)>::max()) {
      |                                           ^~~~~~~~~~~~~~~~~~~~
src/kdb.cc:695:43: ошибка: expected «)» before «decltype»
  695 |     if (num_groups == std::numeric_limits<decltype(num_groups)>::max()) {
      |        ~                                  ^~~~~~~~~~~~~~~~~~~~
      |                                           )
src/kdb.cc: В lambda функции:
src/kdb.cc:706:21: ошибка: loop variable «entry» creates a copy from type «const std::shared_ptr<keepass::Entry>» [-Werror=range-loop-construct]
  706 |     for (const auto entry : group->Entries()) {
      |                     ^~~~~
src/kdb.cc:706:21: замечание: use reference type to prevent copying
  706 |     for (const auto entry : group->Entries()) {
      |                     ^~~~~
      |                     &
src/kdb.cc:709:31: ошибка: «numeric_limits» не является элементом «std»
  709 |       if (num_entries == std::numeric_limits<decltype(num_entries)>::max()) {
      |                               ^~~~~~~~~~~~~~
src/kdb.cc:709:46: ошибка: expected primary-expression before «decltype»
  709 |       if (num_entries == std::numeric_limits<decltype(num_entries)>::max()) {
      |                                              ^~~~~~~~~~~~~~~~~~~~~
src/kdb.cc:709:46: ошибка: expected «)» before «decltype»
  709 |       if (num_entries == std::numeric_limits<decltype(num_entries)>::max()) {
      |          ~                                   ^~~~~~~~~~~~~~~~~~~~~
      |                                              )
cc1plus: все предупреждения считаются ошибками
make: *** [Makefile:24: build/debug/obj/kdb.o] Ошибка 1
make: *** Ожидание завершения заданий…

**Comment by PR070CRYP70N1C** [comment]
Hello, you could not explain how to use your library???

**Comment by PR070CRYP70N1C** [comment]
Numeric_Limits error can be fixed using <limits>

**Comment by kindahl** [comment]
Not sure exactly what compiler version or platform you're using, but fixing any issues should be fairly straight forward.

I just did a test compile (haven't done that in a while) and fixed a couple of warnings turned errors with Clang. If you don't want to deal with the warnings/errors I suggest tweaking the compiler settings in the various `*_CCFLAGS` in `Makefile`. Remove `-Wextra` or maybe `-Werror`.
